app:
  config:
    keycloak:
      server-url: https://auth.nucleo.rocks
      realm: nucleo-dash-realm
      clientId: admin-cli
      client-secret: 6PA7fEn0poAvkXDPaKxcUIqOCHBv9u2m
      user: admin
      pass: admin

