app:
  config:
    keycloak:
      server-url: https://auth.nucleo.rocks
      realm: nucleo-dash-realm
      clientId: admin-cli
      client-secret: vTlGnoGISHDN5YXxYKVOhKq1cthjiqrt
      user: admin
      pass: admin

