
google:
  secret:
    key:
      path: classpath:keys/client_secret_gd.json
  oauth:
    callback:
      uri: http://localhost:4200/calendar/authGoogle

  credentials:
    folder:
      path: file:C:\\Users\\juanros13\\Documents\\CODIGO\\NUCLEO2.0\\credentials
