
google:
  secret:
    key:
      path: classpath:keys/client_secret_gd.json
  oauth:
    callback:
      uri: http://localhost:9001/oauth

  credentials:
    folder:
      path: file:C:\\Users\\juanros13\\Documents\\CODIGO\\credentials
